config/routes.rb
Rails.application.routes.draw do

  root 'video_games#index'

  get 'video_games/add'

  get 'video_games/index'

  get 'video_games/show'

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  belongs_to :video_game
end

app/models/video_game.rb
class VideoGame < ActiveRecord::Base
  has_many :analysis
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  def add
    # Temporary
    if params["name"] and params["description"] and params["editor"]
      @video_game = VideoGame.create(name: params["name"], editor: params["editor"], description: params["description"])
    end
  end

  def index
    @video_games = VideoGame.all
    if not @video_games.any?
      @video_games = [
        VideoGame.new(name: 'Some beautiful name', editor: 'Editor name should be here', description: 'Awesome description'),
        VideoGame.new(name: 'Other test name', editor: 'Greatest editor', description: 'Test description'),
      ]
    end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoGameRating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/video_games/add.html.erb
<h1>VideoGames</h1>

<h1>VideoGameAnalysis</h1>
<h2>Add page</h2>

<%= form_tag(video_games_add_path, method: "get") do %>
  <%= label_tag(:name, "Name:") %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:editor, "Editor:") %>
  <%= text_field_tag(:editor) %>
  <%= label_tag(:description, "Description:") %>
  <%= text_field_tag(:description) %>
  <%= submit_tag("Add") %>
<% end %>

app/views/video_games/index.html.erb
<h1>VideoGames</h1>

<%= link_to 'Add', video_games_add_path %>

<% if @video_games.any? %>
  <ul>
    <% @video_games.each do |video_game| %>
      <li>
        <span class="video-game-name">
          <%= video_game.name %>
        </span>
        <p>Editor: <%= video_game.editor %></p>
        <p>Description: <%= video_game.description %></p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/video_games/show.html.erb
<h1>VideoGames#show</h1>
<p>Find me in app/views/video_games/show.html.erb</p>